// src/constants/actionTypes.js

export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE";

export const FETCH_APPLIED_JOBS_REQUEST = "FETCH_APPLIED_JOBS_REQUEST";
export const FETCH_APPLIED_JOBS_SUCCESS = "FETCH_APPLIED_JOBS_SUCCESS";
export const FETCH_APPLIED_JOBS_FAILURE = "FETCH_APPLIED_JOBS_FAILURE";

export const APPLY_TO_JOB_REQUEST = "APPLY_TO_JOB_REQUEST";
export const APPLY_TO_JOB_SUCCESS = "APPLY_TO_JOB_SUCCESS";
export const APPLY_TO_JOB_FAILURE = "APPLY_TO_JOB_FAILURE";

export const FETCH_APPLICANTS_REQUEST = "FETCH_APPLICANTS_REQUEST";
export const FETCH_APPLICANTS_SUCCESS = "FETCH_APPLICANTS_SUCCESS";
export const FETCH_APPLICANTS_FAILURE = "FETCH_APPLICANTS_FAILURE";

export const FETCH_EMPLOYER_JOBS_SUCCESS = "FETCH_EMPLOYER_JOBS_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const TOGGLE_THEME = "TOGGLE_THEME";
